version: "3.9"
services:
  drone-manager-db:
    container_name: drone_manager_container
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "drones_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /database

networks:
  drone-manager:
    driver: bridge