spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/drones_db"
    username: "postgres"
    password: "postgres"
  flyway:
    schemas: drones_manager
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
  lombok:
    anyConstructor:
      addConstructorProperties: true